# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jiemian.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 501)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(795, 501))
        MainWindow.setMaximumSize(QtCore.QSize(795, 501))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setGeometry(QtCore.QRect(630, 160, 161, 41))
        self.startPushButton.setObjectName("startPushButton")
        self.destTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.destTypeComboBox.setGeometry(QtCore.QRect(160, 20, 411, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destTypeComboBox.sizePolicy().hasHeightForWidth())
        self.destTypeComboBox.setSizePolicy(sizePolicy)
        self.destTypeComboBox.setObjectName("destTypeComboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 21, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.destFilelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.destFilelineEdit.setEnabled(False)
        self.destFilelineEdit.setGeometry(QtCore.QRect(160, 180, 411, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destFilelineEdit.sizePolicy().hasHeightForWidth())
        self.destFilelineEdit.setSizePolicy(sizePolicy)
        self.destFilelineEdit.setObjectName("destFilelineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.srcFileLineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.srcFileLineEdit1.setEnabled(False)
        self.srcFileLineEdit1.setGeometry(QtCore.QRect(160, 100, 411, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcFileLineEdit1.sizePolicy().hasHeightForWidth())
        self.srcFileLineEdit1.setSizePolicy(sizePolicy)
        self.srcFileLineEdit1.setObjectName("srcFileLineEdit1")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.srcFileLineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.srcFileLineEdit2.setEnabled(False)
        self.srcFileLineEdit2.setGeometry(QtCore.QRect(160, 140, 411, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcFileLineEdit2.sizePolicy().hasHeightForWidth())
        self.srcFileLineEdit2.setSizePolicy(sizePolicy)
        self.srcFileLineEdit2.setObjectName("srcFileLineEdit2")
        self.addSrcFilePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addSrcFilePushButton.setGeometry(QtCore.QRect(630, 20, 161, 41))
        self.addSrcFilePushButton.setObjectName("addSrcFilePushButton")
        self.addDestFilePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addDestFilePushButton.setGeometry(QtCore.QRect(630, 90, 161, 41))
        self.addDestFilePushButton.setObjectName("addDestFilePushButton")
        self.logMessageTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logMessageTextEdit.setEnabled(True)
        self.logMessageTextEdit.setGeometry(QtCore.QRect(10, 220, 781, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logMessageTextEdit.sizePolicy().hasHeightForWidth())
        self.logMessageTextEdit.setSizePolicy(sizePolicy)
        self.logMessageTextEdit.setReadOnly(True)
        self.logMessageTextEdit.setObjectName("logMessageTextEdit")
        self.moduleTypeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.moduleTypeLineEdit.setGeometry(QtCore.QRect(160, 60, 411, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleTypeLineEdit.sizePolicy().hasHeightForWidth())
        self.moduleTypeLineEdit.setSizePolicy(sizePolicy)
        self.moduleTypeLineEdit.setObjectName("moduleTypeLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.destTypeComboBox.currentIndexChanged['int'].connect(MainWindow.destTypeChanged)
        self.startPushButton.clicked.connect(MainWindow.startMakedownloadFile)
        self.addSrcFilePushButton.clicked.connect(MainWindow.addSrcFile)
        self.addDestFilePushButton.clicked.connect(MainWindow.chooseDestFile)
        self.moduleTypeLineEdit.textEdited['QString'].connect(MainWindow.editModuleNameSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.destTypeComboBox, self.moduleTypeLineEdit)
        MainWindow.setTabOrder(self.moduleTypeLineEdit, self.addSrcFilePushButton)
        MainWindow.setTabOrder(self.addSrcFilePushButton, self.addDestFilePushButton)
        MainWindow.setTabOrder(self.addDestFilePushButton, self.startPushButton)
        MainWindow.setTabOrder(self.startPushButton, self.srcFileLineEdit1)
        MainWindow.setTabOrder(self.srcFileLineEdit1, self.srcFileLineEdit2)
        MainWindow.setTabOrder(self.srcFileLineEdit2, self.destFilelineEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startPushButton.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "目标类型"))
        self.label_2.setText(_translate("MainWindow", "模块名称"))
        self.label_3.setText(_translate("MainWindow", "输出文件"))
        self.label_4.setText(_translate("MainWindow", "源文件1"))
        self.label_5.setText(_translate("MainWindow", "源文件2"))
        self.addSrcFilePushButton.setText(_translate("MainWindow", "选择源文件"))
        self.addDestFilePushButton.setText(_translate("MainWindow", "选择输出文件"))
